<!--Copyright (c) 2025 Payfast (Pty) Ltd-->
<?php
/** @noinspection PhpUndefinedVariableInspection */
if ($instructions = $block->getMethod()->getInstructions()): ?>
    <div class="items <?=
    $escaper->escapeHtml($block->getMethodCode()) ?> instructions agreement content" id="payment_form_<?=
    $escaper->escapeHtml($block->getMethodCode()) ?>" style="display: none;">
        <?=
        $escaper->escapeHtml(nl2br($instructions)) ?>
    </div>
<?php
endif; ?>
